/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#dae2fd",
        "error-container": "#93000a",
        "on-tertiary": "#003640",
        "on-error": "#690005",
        "surface-bright": "#31394d",
        "tertiary-fixed": "#acedff",
        "on-surface-variant": "#c7c4d7",
        "secondary-fixed": "#f0dbff",
        "surface-container-highest": "#2d3449",
        error: "#ffb4ab",
        "on-tertiary-container": "#002f38",
        "on-surface": "#dae2fd",
        tertiary: "#4cd7f6",
        "surface-container": "#171f33",
        "surface-variant": "#2d3449",
        "primary-container": "#8083ff",
        "on-error-container": "#ffdad6",
        "surface-tint": "#c0c1ff",
        "inverse-primary": "#494bd6",
        "on-primary-container": "#0d0096",
        "on-primary": "#1000a9",
        background: "#0b1326",
        secondary: "#ddb7ff",
        "primary-fixed": "#e1e0ff",
        "on-primary-fixed-variant": "#2f2ebe",
        "surface-container-low": "#131b2e",
        "outline-variant": "#464554",
        "on-secondary-fixed-variant": "#6900b3",
        "primary-fixed-dim": "#c0c1ff",
        "tertiary-container": "#009eb9",
        "on-primary-fixed": "#07006c",
        "surface-container-high": "#222a3d",
        "tertiary-fixed-dim": "#4cd7f6",
        "on-secondary-fixed": "#2c0051",
        surface: "#0b1326",
        "on-secondary-container": "#d6a9ff",
        "surface-dim": "#0b1326",
        outline: "#908fa0",
        "surface-container-lowest": "#060e20",
        primary: "#c0c1ff",
        "secondary-fixed-dim": "#ddb7ff",
        "on-tertiary-fixed": "#001f26",
        "inverse-on-surface": "#283044",
        "on-secondary": "#490080",
        "secondary-container": "#6f00be",
        "on-tertiary-fixed-variant": "#004e5c",
        "on-background": "#dae2fd",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "12px",
        "stack-md": "24px",
        gutter: "24px",
        "section-gap": "120px",
        "stack-lg": "48px",
        unit: "4px",
        "margin-page": "clamp(1.5rem, 5vw, 4rem)",
        "container-max": "1280px",
      },
      fontFamily: {
        h3: ["Inter", "sans-serif"],
        code: ["Space Grotesk", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Space Grotesk", "sans-serif"],
        h2: ["Inter", "sans-serif"],
        h1: ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        h3: ["1.5rem", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "600" }],
        code: ["0.875rem", { lineHeight: "1.5", fontWeight: "400" }],
        "body-md": ["1rem", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "label-caps": ["0.75rem", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        h2: ["2.5rem", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        h1: ["4rem", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "body-lg": ["1.125rem", { lineHeight: "1.7", letterSpacing: "0", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};
